In [1]:
import torch
import numpy as np
from utilities import OptimizedKernel
from tkernels import Matern, Gaussian

In [2]:
def generate_data(desired_A, noise=False):
    X = torch.randn(1000, 2)

    # Transform X with A
    X_transformed = X @ desired_A
    
    # Generate y based on X_transformed and some noise
    noise_data = torch.zeros(1000)
    if noise:
        noise_data = torch.randn(1000)
    y = X_transformed[:, 0] + X_transformed[:, 1] # + torch.randn(1000)
    return X, y

In [3]:
# Init the model
model = OptimizedKernel(kernel=Gaussian(), dim=2, reg_para=1e-4, learning_rate=1e-3, n_epochs=1000, 
                                                flag_initialize_diagonal=True,
                                                flag_symmetric_A=False)

In [4]:
# Define the desired transformation matrix (self.A) and generate Data
desired_A = torch.tensor([[3, 0.0], [0.0, 1]])
X, y = generate_data(desired_A)

In [5]:
# Optimize the model (learn A)
model.optimize(X, y, flag_optim_verbose=False)

In [6]:
# Compare the learned A with the desired A
print("Desired A:\n", desired_A.numpy())
print("Learned A:\n", model.A.detach().numpy().round(decimals=3))

Desired A:
 [[3. 0.]
 [0. 1.]]
Learned A:
 [[2.885 1.11 ]
 [0.545 1.221]]


In [7]:
# Use different transformation matrix
desired_A = torch.tensor([[1.0, 0.0], [0.0, 3.0]])
X, y = generate_data(desired_A)

In [8]:
# Optimize the model (learn A)
model.optimize(X, y, flag_optim_verbose=False)

In [9]:
# Compare the learned A with the desired A
print("Desired A:\n", desired_A.numpy())
print("Learned A:\n", model.A.detach().numpy().round(decimals=3))

Desired A:
 [[1. 0.]
 [0. 3.]]
Learned A:
 [[1.227 0.499]
 [1.156 2.875]]


In [10]:
# Use symmetric A
model = OptimizedKernel(kernel=Gaussian(), dim=2, reg_para=1e-4, learning_rate=1e-3, n_epochs=1000, 
                                                flag_initialize_diagonal=True,
                                                flag_symmetric_A=True)

In [11]:
# Same data
model.optimize(X, y, flag_optim_verbose=False)

In [12]:
# Compare the learned A with the desired A
print("Desired A:\n", desired_A.numpy())
print("Learned A:\n", model.A.detach().numpy().round(decimals=3))

Desired A:
 [[1. 0.]
 [0. 3.]]
Learned A:
 [[1.133 0.708]
 [0.708 3.068]]


In [13]:
# Higher Regression Parameter
model = OptimizedKernel(kernel=Gaussian(), dim=2, reg_para=5e-3, learning_rate=1e-3, n_epochs=1000, 
                                                flag_initialize_diagonal=True,
                                                flag_symmetric_A=True)

In [14]:
# Same data
model.optimize(X, y, flag_optim_verbose=False)

In [15]:
# Compare the learned A with the desired A
print("Desired A:\n", desired_A.numpy())
print("Learned A:\n", model.A.detach().numpy().round(decimals=3))

Desired A:
 [[1. 0.]
 [0. 3.]]
Learned A:
 [[0.042 0.087]
 [0.087 0.276]]


In [16]:
# Init A with random Matrix
model = OptimizedKernel(kernel=Gaussian(), dim=2, reg_para=1e-4, learning_rate=1e-3, n_epochs=1000, 
                                                flag_initialize_diagonal=False,
                                                flag_symmetric_A=False)

In [17]:
# Same data
model.optimize(X, y, flag_optim_verbose=False)

In [18]:
# Compare the learned A with the desired A
print("Desired A:\n", desired_A.numpy())
print("Learned A:\n", model.A.detach().numpy().round(decimals=3))

Desired A:
 [[1. 0.]
 [0. 3.]]
Learned A:
 [[0.036 0.041]
 [0.122 0.111]]


In [19]:
# Data with noise
desired_A = torch.tensor([[3.0, 0.0], [0.0, 1.0]])
X, y = generate_data(desired_A, noise=True)

In [20]:
# Init the model
model = OptimizedKernel(kernel=Gaussian(), dim=2, reg_para=1e-4, learning_rate=1e-3, n_epochs=1000, 
                                                flag_initialize_diagonal=True,
                                                flag_symmetric_A=False)

In [21]:
model.optimize(X, y, flag_optim_verbose=False)

In [22]:
# Compare the learned A with the desired A
print("Desired A:\n", desired_A.numpy())
print("Learned A:\n", model.A.detach().numpy().round(decimals=3))

Desired A:
 [[3. 0.]
 [0. 1.]]
Learned A:
 [[3.06  1.2  ]
 [0.592 1.308]]
