In [1]:
import torch
import numpy as np
from utilities import OptimizedKernel
from tkernels import Matern, Gaussian

In [2]:
def generate_data(desired_A):
    X = torch.randn(1000, 2)

    # Transform X with A
    X_transformed = X @ desired_A

    # Generate y based on X_transformed and some noise
    y = X_transformed[:, 0] + X_transformed[:, 1] # + torch.randn(1000)
    return X, y

In [3]:
# Init the model
model = OptimizedKernel(kernel=Gaussian(), dim=2, reg_para=1e-4, learning_rate=1e-3, n_epochs=1000, 
                                                flag_initialize_diagonal=True,
                                                flag_symmetric_A=False)

In [4]:
# Define the desired transformation matrix (self.A) and generate Data
desired_A = torch.tensor([[0.5, 0.0], [0.0, 2.0]])
X, y = generate_data(desired_A)

In [5]:
# Optimize the model (learn A)
model.optimize(X, y, flag_optim_verbose=False)

In [6]:
# Compare the learned A with the desired A
print("Desired A:\n", desired_A.numpy())
print("Learned A:\n", model.A.detach().numpy())

Desired A:
 [[0.5 0. ]
 [0.  2. ]]
Learned A:
 [[1.1555288 0.4581991]
 [1.1114368 3.0176654]]


In [7]:
# Use different transformation matrix
desired_A = torch.tensor([[3.0, 0.0], [0.0, 1.0]])
X, y = generate_data(desired_A)

In [8]:
# Optimize the model (learn A)
model.optimize(X, y, flag_optim_verbose=False)

In [9]:
# Compare the learned A with the desired A
print("Desired A:\n", desired_A.numpy())
print("Learned A:\n", model.A.detach().numpy())

Desired A:
 [[3. 0.]
 [0. 1.]]
Learned A:
 [[2.8908656 1.2014633]
 [0.559028  1.1843873]]


In [10]:
# Use symmetric A
model = OptimizedKernel(kernel=Gaussian(), dim=2, reg_para=1e-4, learning_rate=1e-3, n_epochs=1000, 
                                                flag_initialize_diagonal=True,
                                                flag_symmetric_A=True)

In [11]:
# Same data
model.optimize(X, y, flag_optim_verbose=False)

In [12]:
# Compare the learned A with the desired A
print("Desired A:\n", desired_A.numpy())
print("Learned A:\n", model.A.detach().numpy())

Desired A:
 [[3. 0.]
 [0. 1.]]
Learned A:
 [[3.0643759  0.69086426]
 [0.69086426 1.0996428 ]]


In [13]:
# Higher Regression Parameter
model = OptimizedKernel(kernel=Gaussian(), dim=2, reg_para=1e-3, learning_rate=1e-3, n_epochs=1000, 
                                                flag_initialize_diagonal=True,
                                                flag_symmetric_A=True)

In [14]:
# Same data
model.optimize(X, y, flag_optim_verbose=False)

In [15]:
# Compare the learned A with the desired A
print("Desired A:\n", desired_A.numpy())
print("Learned A:\n", model.A.detach().numpy())

Desired A:
 [[3. 0.]
 [0. 1.]]
Learned A:
 [[0.19514006 0.073038  ]
 [0.073038   0.00905121]]


In [22]:
# Init A with random Matrix
model = OptimizedKernel(kernel=Gaussian(), dim=2, reg_para=1e-4, learning_rate=1e-4, n_epochs=1000, 
                                                flag_initialize_diagonal=False,
                                                flag_symmetric_A=False)

In [23]:
# Same data
model.optimize(X, y, flag_optim_verbose=False)

In [24]:
# Compare the learned A with the desired A
print("Desired A:\n", desired_A.numpy())
print("Learned A:\n", model.A.detach().numpy())

Desired A:
 [[3. 0.]
 [0. 1.]]
Learned A:
 [[0.36803505 0.02286587]
 [0.1214494  0.01511656]]
