In [47]:
import torch
import numpy as np
from utilities import OptimizedKernel
from tkernels import Matern, Gaussian

In [48]:
def generate_data(desired_A, noise=False, size=(10000, 2)):
    X = torch.rand(size)

    # Transform X with A
    X_transformed = X @ desired_A
    
    # Generate y based on X_transformed and some noise
    noise_data = torch.zeros(size[0])
    if noise:
        noise_data = torch.rand(size[0])
    y = X_transformed[:, 0] + X_transformed[:, 1] + 0.1 * noise_data
    return X, y

In [55]:
# Init the model
model = OptimizedKernel(kernel=Gaussian(), dim=2, reg_para=1e-6, learning_rate=1e-3, n_epochs=50, 
                                                flag_initialize_diagonal=True,
                                                flag_symmetric_A=False)

In [56]:
# Define the desired transformation matrix (self.A) and generate Data
desired_A = torch.tensor([[3, 0.0], [0.0, 1]])
X, y = generate_data(desired_A)

In [57]:
# Optimize the model (learn A)
model.optimize(X, y, flag_optim_verbose=False)

In [58]:
# Compare the learned A with the desired A
print("Desired A:\n", desired_A.numpy())
print("Learned A:\n", model.A.detach().numpy().round(decimals=3))

Desired A:
 [[3. 0.]
 [0. 1.]]
Learned A:
 [[0.424 0.048]
 [0.053 0.266]]


In [59]:
U, S, VT = np.linalg.svd(model.A.detach().numpy().round(decimals=3))
print("Singulärwerte (S):", S.round(decimals=3))
print("Linke singuläre Vektoren (U):\n", U.round(decimals=3))
print("Rechte singuläre Vektoren (V^T):\n", VT.round(decimals=3))

# Eigenwerte und Eigenvektoren berechnen
eigenwerte, eigenvektoren = np.linalg.eig(model.A.detach().numpy().round(decimals=3))

# Ausgabe der Eigenwerte und Eigenvektoren
print("Eigenwerte:", eigenwerte)
print("Eigenvektoren:\n", eigenvektoren)

Singulärwerte (S): [0.439 0.251]
Linke singuläre Vektoren (U):
 [[-0.959 -0.284]
 [-0.284  0.959]]
Rechte singuläre Vektoren (V^T):
 [[-0.961 -0.277]
 [-0.277  0.961]]
Eigenwerte: [0.43872833 0.25127167]
Eigenvektoren:
 [[ 0.95600766 -0.26774696]
 [ 0.29334164  0.96348923]]


In [8]:
# Use different transformation matrix
desired_A = torch.tensor([[1.0, 0.0], [0.0, 3.0]])
X, y = generate_data(desired_A)

In [9]:
# Optimize the model (learn A)
model.optimize(X, y, flag_optim_verbose=False)

In [10]:
# Compare the learned A with the desired A
print("Desired A:\n", desired_A.numpy())
print("Learned A:\n", model.A.detach().numpy().round(decimals=3))

Desired A:
 [[1. 0.]
 [0. 3.]]
Learned A:
 [[0.259 0.029]
 [0.1   0.416]]


In [11]:
U, S, VT = np.linalg.svd(model.A.detach().numpy().round(decimals=3))
print("Singulärwerte (S):", S.round(decimals=3))
print("Linke singuläre Vektoren (U):\n", U.round(decimals=3))
print("Rechte singuläre Vektoren (V^T):\n", VT.round(decimals=3))

Singulärwerte (S): [0.441 0.238]
Linke singuläre Vektoren (U):
 [[ 0.287  0.958]
 [ 0.958 -0.287]]
Rechte singuläre Vektoren (V^T):
 [[ 0.386  0.922]
 [ 0.922 -0.386]]


In [12]:
# Use symmetric A
model = OptimizedKernel(kernel=Gaussian(), dim=2, reg_para=1e-6, learning_rate=1e-3, n_epochs=1000, 
                                                flag_initialize_diagonal=True,
                                                flag_symmetric_A=True)

In [13]:
# Same data
model.optimize(X, y, flag_optim_verbose=False)

In [14]:
# Compare the learned A with the desired A
print("Desired A:\n", desired_A.numpy())
print("Learned A:\n", model.A.detach().numpy().round(decimals=3))

Desired A:
 [[1. 0.]
 [0. 3.]]
Learned A:
 [[0.243 0.056]
 [0.056 0.423]]


In [15]:
U, S, VT = np.linalg.svd(model.A.detach().numpy().round(decimals=3))
print("Singulärwerte (S):", S.round(decimals=3))
print("Linke singuläre Vektoren (U):\n", U.round(decimals=3))
print("Rechte singuläre Vektoren (V^T):\n", VT.round(decimals=3))

Singulärwerte (S): [0.439 0.227]
Linke singuläre Vektoren (U):
 [[ 0.275  0.962]
 [ 0.962 -0.275]]
Rechte singuläre Vektoren (V^T):
 [[ 0.275  0.962]
 [ 0.962 -0.275]]


In [16]:
# Higher Regression Parameter
model = OptimizedKernel(kernel=Gaussian(), dim=2, reg_para=5e-3, learning_rate=1e-3, n_epochs=1000, 
                                                flag_initialize_diagonal=True,
                                                flag_symmetric_A=True)

In [17]:
# Same data
model.optimize(X, y, flag_optim_verbose=False)

In [18]:
# Compare the learned A with the desired A
print("Desired A:\n", desired_A.numpy())
print("Learned A:\n", model.A.detach().numpy().round(decimals=3))

Desired A:
 [[1. 0.]
 [0. 3.]]
Learned A:
 [[0.13  0.39 ]
 [0.39  1.169]]


In [19]:
U, S, VT = np.linalg.svd(model.A.detach().numpy().round(decimals=3))
print("Singulärwerte (S):", S.round(decimals=3))
print("Linke singuläre Vektoren (U):\n", U.round(decimals=3))
print("Rechte singuläre Vektoren (V^T):\n", VT.round(decimals=3))

Singulärwerte (S): [1.299 0.   ]
Linke singuläre Vektoren (U):
 [[-0.316 -0.949]
 [-0.949  0.316]]
Rechte singuläre Vektoren (V^T):
 [[-0.316 -0.949]
 [ 0.949 -0.316]]


In [20]:
# Init A with random Matrix
model = OptimizedKernel(kernel=Gaussian(), dim=2, reg_para=1e-5, learning_rate=1e-3, n_epochs=1000, 
                                                flag_initialize_diagonal=False,
                                                flag_symmetric_A=False)

In [21]:
# Same data
model.optimize(X, y, flag_optim_verbose=False)

In [22]:
# Compare the learned A with the desired A
print("Desired A:\n", desired_A.numpy())
print("Learned A:\n", model.A.detach().numpy().round(decimals=3))

Desired A:
 [[1. 0.]
 [0. 3.]]
Learned A:
 [[ 0.026  0.192]
 [-0.038  0.524]]


In [23]:
U, S, VT = np.linalg.svd(model.A.detach().numpy().round(decimals=3))
print("Singulärwerte (S):", S.round(decimals=3))
print("Linke singuläre Vektoren (U):\n", U.round(decimals=3))
print("Rechte singuläre Vektoren (V^T):\n", VT.round(decimals=3))

Singulärwerte (S): [0.559 0.037]
Linke singuläre Vektoren (U):
 [[ 0.341  0.94 ]
 [ 0.94  -0.341]]
Rechte singuläre Vektoren (V^T):
 [[-0.048  0.999]
 [ 0.999  0.048]]


In [24]:
# Data with noise
desired_A = torch.tensor([[3.0, 0.0], [0.0, 1.0]])
X, y = generate_data(desired_A, noise=True)

In [25]:
# Init the model
model = OptimizedKernel(kernel=Gaussian(), dim=2, reg_para=1e-5, learning_rate=1e-3, n_epochs=1000, 
                                                flag_initialize_diagonal=False,
                                                flag_symmetric_A=False)

In [26]:
model.optimize(X, y, flag_optim_verbose=False)

In [27]:
# Compare the learned A with the desired A
print("Desired A:\n", desired_A.numpy())
print("Learned A:\n", model.A.detach().numpy().round(decimals=3))

Desired A:
 [[3. 0.]
 [0. 1.]]
Learned A:
 [[ 0.026 -0.031]
 [ 0.005 -0.014]]


In [28]:
U, S, VT = np.linalg.svd(model.A.detach().numpy().round(decimals=3))
print("Singulärwerte (S):", S.round(decimals=3))
print("Linke singuläre Vektoren (U):\n", U.round(decimals=3))
print("Rechte singuläre Vektoren (V^T):\n", VT.round(decimals=3))

Singulärwerte (S): [0.043 0.005]
Linke singuläre Vektoren (U):
 [[-0.944 -0.33 ]
 [-0.33   0.944]]
Rechte singuläre Vektoren (V^T):
 [[-0.612  0.791]
 [-0.791 -0.612]]


In [29]:
desired_A = torch.tensor([[3.0, 0.0], [0.0, 0.0]])
X, y = generate_data(desired_A)

In [30]:
model = OptimizedKernel(kernel=Gaussian(), dim=2, reg_para=1e-6, learning_rate=1e-3, n_epochs=1000, 
                                                flag_initialize_diagonal=False,
                                                flag_symmetric_A=False)

In [31]:
model.optimize(X, y, flag_optim_verbose=False)

In [32]:
# Compare the learned A with the desired A
print("Desired A:\n", desired_A.numpy())
print("Learned A:\n", model.A.detach().numpy().round(decimals=3))

Desired A:
 [[3. 0.]
 [0. 0.]]
Learned A:
 [[ 0.484 -0.049]
 [ 0.021  0.212]]


In [33]:
U, S, VT = np.linalg.svd(model.A.detach().numpy().round(decimals=3))
print("Singulärwerte (S):", S.round(decimals=3))
print("Linke singuläre Vektoren (U):\n", U.round(decimals=3))
print("Rechte singuläre Vektoren (V^T):\n", VT.round(decimals=3))

Singulärwerte (S): [0.486 0.213]
Linke singuläre Vektoren (U):
 [[-1.     0.001]
 [ 0.001  1.   ]]
Rechte singuläre Vektoren (V^T):
 [[-0.995  0.101]
 [ 0.101  0.995]]


In [34]:
# Transformationmatrix
desired_A = torch.tensor([[1, 0.0], [0.0, 3]])
desired_A2 = torch.tensor([[3, 0.0], [0.0, 1]])
X, y = generate_data(desired_A2, size=(10000, 2))
model = OptimizedKernel(kernel=Gaussian(), dim=2, reg_para=1e-6, learning_rate=1e-3, n_epochs=1000, 
                                                flag_initialize_diagonal=desired_A.clone(),
                                                flag_symmetric_A=False)

In [35]:
model.optimize(X, y, flag_optim_verbose=False)

In [36]:
# Compare the learned A with the desired A
print("Init A:\n", desired_A.numpy())
print("Desired A:\n", desired_A2.numpy())
print("Learned A:\n", model.A.detach().numpy().round(decimals=3))

Init A:
 [[1. 0.]
 [0. 3.]]
Desired A:
 [[3. 0.]
 [0. 1.]]
Learned A:
 [[ 0.657 -0.11 ]
 [ 0.004  2.674]]


In [37]:
U, S, VT = np.linalg.svd(model.A.detach().numpy().round(decimals=3))
print("Singulärwerte (S):", S.round(decimals=3))
print("Linke singuläre Vektoren (U):\n", U.round(decimals=3))
print("Rechte singuläre Vektoren (V^T):\n", VT.round(decimals=3))

Singulärwerte (S): [2.676 0.657]
Linke singuläre Vektoren (U):
 [[-0.043  0.999]
 [ 0.999  0.043]]
Rechte singuläre Vektoren (V^T):
 [[-0.009  1.   ]
 [ 1.     0.009]]


In [38]:
# Matern Kernel
desired_A = torch.tensor([[1, 0.0], [0.0, 3]])
X, y = generate_data(desired_A2, size=(10000, 2))
model = OptimizedKernel(kernel=Matern(k=2), dim=2, reg_para=1e-6, learning_rate=1e-3, n_epochs=1000, 
                                                flag_initialize_diagonal=True,
                                                flag_symmetric_A=False)

In [39]:
model.optimize(X, y, flag_optim_verbose=False)

In [40]:
# Compare the learned A with the desired A
print("Desired A:\n", desired_A2.numpy())
print("Learned A:\n", model.A.detach().numpy().round(decimals=3))

Desired A:
 [[3. 0.]
 [0. 1.]]
Learned A:
 [[ 1.066  0.148]
 [-0.043  0.862]]


In [41]:
U, S, VT = np.linalg.svd(model.A.detach().numpy().round(decimals=3))
print("Singulärwerte (S):", S.round(decimals=3))
print("Linke singuläre Vektoren (U):\n", U.round(decimals=3))
print("Rechte singuläre Vektoren (V^T):\n", VT.round(decimals=3))

Singulärwerte (S): [1.083 0.854]
Linke singuläre Vektoren (U):
 [[-0.982 -0.187]
 [-0.187  0.982]]
Rechte singuläre Vektoren (V^T):
 [[-0.959 -0.283]
 [-0.283  0.959]]
