In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from vkoga_2L import VKOGA_2L
from kernels import Matern, Gaussian

In [2]:
def generate_data(n_samples=500, n_features=3, n_targets=2):
    A_true = A_true = np.array([[2, -1, 0.5], [0.5, 1, -0.5], [1, 1, 2]])  # True transformation matrix to calc X and compare later to learned A
    X = np.random.randn(n_samples, n_features)
    X_transformed = X @ A_true
    kernel = Matern(k=2)
    K = kernel.eval(X_transformed, X_transformed)
    # y = K @ np.random.randn(n_samples, 2)
    y = np.dot(X, A_true) + 0.0 * np.random.randn(n_samples, n_features)  # Calculating A with optionally some noise
    return X, y, A_true

In [3]:
# Initialize VKOGA_2L model (some Parameters are described in Page 123)
model = VKOGA_2L(
    kernel=[Matern(k=2), Matern(k=2)], # quadratic Matern kernel used
    flag_2L_optimization=True,
    verbose=True,
    greedy_type='f_greedy',
    reg_par=1e-2,
    restr_par=1e-2,
    tol_f=1e-10,
    tol_p=1e-10,
    reg_para_optim=0,
    learning_rate=5e-3,
    n_epochs_optim=100,
    batch_size=32
)

In [4]:
# Generate data
X, y, A_true = generate_data(n_samples=500, n_features=3, n_targets=2)
# Split into training and testing data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [5]:
# Training
model.fit(X_train, y_train)

(400, 3)
(400, 3)


C:\Users\leonk\Desktop\Uni\Barb\Code\VKOGA\src\vkoga\opt_kernel.py:41: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X = torch.tensor(X, dtype=torch.float32)
C:\Users\leonk\Desktop\Uni\Barb\Code\VKOGA\src\vkoga\opt_kernel.py:42: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(y, dtype=torch.float32)


tensor([[ 0.5186, -0.2032,  0.2747],
        [ 0.2505,  1.0181, -0.3759],
        [-0.0625, -0.7332, -2.3227]], requires_grad=True)
torch.Size([32, 32])
tensor([[3.0000, 1.3825, 0.4589,  ..., 1.6435, 1.4010, 1.6288],
        [1.3825, 3.0000, 0.6191,  ..., 1.8334, 2.8295, 0.6055],
        [0.4589, 0.6191, 3.0000,  ..., 1.0935, 0.7649, 0.8027],
        ...,
        [1.6435, 1.8334, 1.0935,  ..., 3.0000, 2.2664, 1.3424],
        [1.4010, 2.8295, 0.7649,  ..., 2.2664, 3.0000, 0.7170],
        [1.6288, 0.6055, 0.8027,  ..., 1.3424, 0.7170, 3.0000]],
       grad_fn=<MulBackward0>)
Epoch 1/100, Loss: 8946.102142
Epoch 2/100, Loss: 8271.230835
Epoch 3/100, Loss: 7662.081665
Epoch 4/100, Loss: 7110.144226
Epoch 5/100, Loss: 6613.167984
Epoch 6/100, Loss: 6166.955780
Epoch 7/100, Loss: 5766.492142
Epoch 8/100, Loss: 5406.710922
Epoch 9/100, Loss: 5082.858627
Epoch 10/100, Loss: 4790.643723
tensor([[ 0.9838, -0.5527,  0.5393],
        [ 0.7985,  1.5218, -0.8410],
        [ 0.1297, -1.2176, -2.757

C:\Users\leonk\Desktop\Uni\Barb\Code\VKOGA\src\vkoga\opt_kernel.py:28: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_tensor = torch.tensor(X, dtype=torch.float32)
C:\Users\leonk\Desktop\Uni\Barb\Code\VKOGA\src\vkoga\opt_kernel.py:29: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  Z_tensor = torch.tensor(Z, dtype=torch.float32)



Epoch 19/100, Loss: 3093.234619
Epoch 20/100, Loss: 2971.872086
tensor([[ 1.2667, -0.8754,  0.8342],
        [ 1.2097,  1.8324, -1.1731],
        [ 0.2222, -1.6383, -3.0845]], requires_grad=True)
Epoch 21/100, Loss: 2859.200974
Epoch 22/100, Loss: 2754.382072
Epoch 23/100, Loss: 2656.673317
Epoch 24/100, Loss: 2565.419685
Epoch 25/100, Loss: 2480.039383
Epoch 26/100, Loss: 2400.016396
Epoch 27/100, Loss: 2324.889893
Epoch 28/100, Loss: 2254.248108
Epoch 29/100, Loss: 2187.723404
Epoch 30/100, Loss: 2124.983803
tensor([[ 1.4672, -1.1364,  1.0882],
        [ 1.5291,  2.0481, -1.4242],
        [ 0.2823, -1.9906, -3.3392]], requires_grad=True)
Epoch 31/100, Loss: 2065.731979
Epoch 32/100, Loss: 2009.699738
Epoch 33/100, Loss: 1956.643890
Epoch 34/100, Loss: 1906.344810
Epoch 35/100, Loss: 1858.602859
Epoch 36/100, Loss: 1813.236267
Epoch 37/100, Loss: 1770.080612
Epoch 38/100, Loss: 1728.984566
Epoch 39/100, Loss: 1689.810730
Epoch 40/100, Loss: 1652.432678
tensor([[ 1.6251, -1.3563,  1.3

VKOGA_2L(flag_2L_optimization=True,
         kernel=<kernels.Matern object at 0x000002197DC79910>,
         n_epochs_optim=100, reg_par=0.01, reg_para_optim=0)

In [6]:
# Predict
predictions = model.predict(X_test)

In [7]:
# Print the first few predictions and ground truth
print("Predictions:", predictions[:5])
print("Ground truth:", y_test[:5])

Predictions: [[-1.84927299  0.13383716 -2.19416916]
 [ 2.34980915  0.00290556 -0.81797546]
 [-2.37478671 -1.17342028 -0.44658202]
 [ 0.47326137  1.28914008  0.85147792]
 [-0.49125884  2.88072599  1.02500689]]
Ground truth: [[-1.89497628  0.12015473 -2.3318907 ]
 [ 2.35952967  0.03464933 -0.93687022]
 [-2.7452759  -1.2277997  -0.32934575]
 [ 0.5376046   1.86692396  1.14995049]
 [-0.42373227  2.9105026   1.03758427]]


In [8]:
# MSE
mse = np.mean((predictions - y_test) ** 2)
print(f"Mean Squared Error on Test Data: {mse:.6f}")

Mean Squared Error on Test Data: 0.418063


In [9]:
# Compare Learnend and original A
print("learned A:")
print(model.A)
print("true A:")
print(A_true)

learned A:
[[ 2.233441  -2.2678554  2.2335498]
 [ 2.8753164  2.768862  -2.3779266]
 [ 0.548826  -3.5922155 -4.3489633]]
true A:
[[ 2.  -1.   0.5]
 [ 0.5  1.  -0.5]
 [ 1.   1.   2. ]]
