In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from vkoga_2L import VKOGA_2L
from kernels import Matern, Gaussian

In [2]:
def generate_data(n_samples=500, n_features=3, n_targets=2):
    A_true = A_true = np.array([[2, -1, 0.5], [0.5, 1, -0.5], [1, 1, 2]])  # True transformation matrix to calc X and compare later to learned A
    X = np.random.randn(n_samples, n_features)
    X_transformed = X @ A_true
    kernel = Matern(k=2)
    K = kernel.eval(X_transformed, X_transformed)
    # y = K @ np.random.randn(n_samples, 2)
    y = np.dot(X, A_true) + 0.0 * np.random.randn(n_samples, n_features)  # Calculating A with optionally some noise
    return X, y, A_true

In [3]:
# Initialize VKOGA_2L model (some Parameters are described in Page 123)
model = VKOGA_2L(
    kernel=[Matern(k=2), Matern(k=2)], # quadratic Matern kernel used
    flag_2L_optimization=True,
    verbose=True,
    greedy_type='f_greedy',
    reg_par=1e-2,
    restr_par=1e-2,
    tol_f=1e-10,
    tol_p=1e-10,
    reg_para_optim=0,
    learning_rate=5e-3,
    n_epochs_optim=100,
    batch_size=32
)

In [4]:
# Generate data
X, y, A_true = generate_data(n_samples=500, n_features=3, n_targets=2)
# Split into training and testing data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [5]:
# Training
model.fit(X_train, y_train)

(400, 3)
(400, 3)


C:\Users\leonk\Desktop\Uni\Barb\Code\VKOGA\src\vkoga\opt_kernel.py:41: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X = torch.tensor(X, dtype=torch.float32)
C:\Users\leonk\Desktop\Uni\Barb\Code\VKOGA\src\vkoga\opt_kernel.py:42: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(y, dtype=torch.float32)


tensor([[-0.0152, -1.7000,  0.4968],
        [ 2.1126, -1.1928, -0.7237],
        [ 0.2034,  1.8554, -0.5366]], requires_grad=True)
torch.Size([32, 32])
tensor([[3.0000, 0.3707, 0.2021,  ..., 0.8029, 0.9432, 0.7742],
        [0.3707, 3.0000, 1.5299,  ..., 1.5136, 0.7015, 0.0406],
        [0.2021, 1.5299, 3.0000,  ..., 1.6877, 0.1812, 0.0146],
        ...,
        [0.8029, 1.5136, 1.6877,  ..., 3.0000, 0.4704, 0.0712],
        [0.9432, 0.7015, 0.1812,  ..., 0.4704, 3.0000, 0.3814],
        [0.7742, 0.0406, 0.0146,  ..., 0.0712, 0.3814, 3.0000]],
       grad_fn=<MulBackward0>)
Epoch 1/100, Loss: 4109.536263
tensor([[ 0.1031, -2.4319,  1.4011],
        [ 2.9672, -1.9885, -1.6972],
        [ 0.6138,  2.3162,  0.1549]], requires_grad=True)

C:\Users\leonk\Desktop\Uni\Barb\Code\VKOGA\src\vkoga\opt_kernel.py:28: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_tensor = torch.tensor(X, dtype=torch.float32)
C:\Users\leonk\Desktop\Uni\Barb\Code\VKOGA\src\vkoga\opt_kernel.py:29: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  Z_tensor = torch.tensor(Z, dtype=torch.float32)



Epoch 21/100, Loss: 1824.872829
tensor([[ 0.2223, -2.9855,  1.8791],
        [ 3.5179, -2.5223, -2.4070],
        [ 0.9925,  2.6677,  0.3569]], requires_grad=True)
Epoch 41/100, Loss: 1204.722086
tensor([[ 0.3588, -3.4144,  2.2665],
        [ 3.9215, -2.9215, -2.9691],
        [ 1.3617,  2.9871,  0.5282]], requires_grad=True)
Epoch 61/100, Loss: 901.708315
tensor([[ 0.5222, -3.7565,  2.6072],
        [ 4.2346, -3.2366, -3.4320],
        [ 1.7240,  3.2795,  0.7219]], requires_grad=True)
Epoch 81/100, Loss: 723.279871

****************************** [VKOGA] ******************************
Training model with
       |_ kernel              : mat2 [gamma = 1.00e+00]
       |_ regularization par. : 1.00e-02
       |_ restriction par.    : 0.00e+00

Training ongoing with
       |_ selected points     :        1 /      100
       |_ train residual      : 1.04e+02 / 1.00e-10
       |_ train power fun     : 3.01e+00 / 1.00e-10
Training ongoing with
       |_ selected points     :       11 /     

VKOGA_2L(flag_2L_optimization=True,
         kernel=<kernels.Matern object at 0x000001E2699C49D0>,
         n_epochs_optim=100, reg_par=0.01, reg_para_optim=0)

In [6]:
# Predict
predictions = model.predict(X_test)

In [7]:
# Print the first few predictions and ground truth
print("Predictions:", predictions[:5])
print("Ground truth:", y_test[:5])

Predictions: [[ 1.32523277 -2.11876436  1.92731621]
 [ 0.39109549  0.16942351  1.36354434]
 [-1.18134633  1.44902994 -2.28022415]
 [ 0.86428329 -0.10736635  0.32847541]
 [ 0.91221364 -0.71678972  1.09054021]]
Ground truth: [[ 1.94517334 -2.64640359  2.65047902]
 [ 2.88095065  1.1805552   6.24799208]
 [-1.10852283  1.65867207 -2.48687846]
 [ 1.24395082 -0.14031138  0.21957853]
 [ 3.86875226 -2.20417387  4.82104431]]


In [8]:
# MSE
mse = np.mean((predictions - y_test) ** 2)
print(f"Mean Squared Error on Test Data: {mse:.6f}")

Mean Squared Error on Test Data: 1.061537


In [9]:
# Compare Learnend and original A
print("learned A:")
print(model.A)
print("true A:")
print(A_true)

learned A:
[[ 0.7008121 -4.040871   2.912227 ]
 [ 4.488795  -3.4954107 -3.8262086]
 [ 2.0710564  3.5444462  0.9256562]]
true A:
[[ 2.  -1.   0.5]
 [ 0.5  1.  -0.5]
 [ 1.   1.   2. ]]
